version: '2.3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  apm:
    build:
      context: apm/
    volumes:
      - ./apm/config/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    ports:
      - "8200:8200"
    environment:
      GENERATE_DASHBOARDS: "true"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601/api/status']
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:

  elk:
    driver: bridge
